= Configure TLS with Hazelcast Platform Operator tutorial
:page-layout: tutorial
:page-product: operator
:page-categories: Cloud Native
:page-lang: go, java
:page-enterprise: true
:page-est-time: 10 mins
:description: Learn how to secure Hazelcast cluster with TLS and Hazelcast Kubernetes Operator.

{description}

== Context
In this tutorial, you'll do the following:

- Create Kubernetes Secret with TLS certificate and key.

- Deploy Hazelcast cluster with TLS (mTLS) encryption enforced between members.

- Deploy Management Center to monitor your Hazelcast cluster.

- Connect to you cluster using TLS to encrypt member to client network traffic.


== Before you Begin

Before starting this tutorial, make sure that you meet the following prerequisites:

* Up and running https://kubernetes.io/[Kubernetes] cluster
* Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
* Deployed xref:operator:ROOT:index.adoc[Hazelcast Platform Operator]
* OpenSSL command-line tool, https://www.openssl.org/[openssl]

== Step 1. Create Kubernetes Secret with TLS certificate and key

. Generate TLS certyfcate and key in PEM format using OpenSSL
+
[source, shell]
----
openssl req -x509 -sha256 -nodes -days 3650 -subj '/CN=example' -addext "subjectAltName=DNS:example" -newkey rsa:2048 -outform pem -keyout example.key -out example.crt -addext "extendedKeyUsage=serverAuth,clientAuth"
----

. Create Kubernetes Secret with TLS certificate and key
+
[source, shell]
----
kubectl create secret tls example --cert=example.crt --key=example.key
----
+
NOTE: In production setup it is advised to use tools like https://cert-manager.io/[cert-manager] to manage your certificates.

== Step 2. Deploy Hazelcast cluster with TLS

. Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
+
[source, shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<hz-license-key>
----

. Create the Hazelcast cluster with TLS configured.
+
[source, yaml]
----
kubectl apply -f - <<EOF
include::ROOT:example$/hazelcast.yaml[]
EOF
----
+
. Run the following commands to check cluster status
+
[source, shell]
----
kubectl get hazelcasts.hazelcast.com hazelcast
NAME        STATUS    MEMBERS   EXTERNAL-ADDRESSES   WAN-ADDRESSES
hazelcast   Running   3/3       172.18.254.1:5701    172.18.254.1:5710
----

== Step 3. Deploy Management Center

Apply the Management Center custom resource

[source, yaml]
----
kubectl apply -f - <<EOF
include::ROOT:example$/managementcenter.yaml[]
EOF
----

== Step 4. Connect to Hazelcast cluster over TLS

Configure the Hazelcast client with the TLS certificate.

[tabs]
====

Java::
+
--
[source, java]
----
include::ROOT:example$/java/src/main/java/com/hazelcast/example.java[]
----
--

NodeJS::
+
--
[source, javascript]
----
include::ROOT:example$/nodejs/example.js[]
----
--

Go::
+
--
[source, go]
----
include::ROOT:example$/go/example.go[]
----
--

Python::
+
--
[source, python]
----
include::ROOT:example$/python/example.py[]
----
--

====

== Step 5. Clean Up

To clean up the created resources remove the all Custom Resources and secrets.

[source, shell]
----
kubectl delete $(kubectl get hazelcast,managementcenter -o name)
kubectl delete secret example
----

== See Also

- xref:operator:ROOT:get-started.adoc[]
- xref:operator:ROOT:deploy-management-center.adoc[]
- xref:operator:ROOT:tls.adoc[]
